services:
  - type: web
    name: autosharts-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm audit fix --force && npx prisma generate && tsc
    startCommand: node dist/server.js
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres:Jamaicanos157%40@db.duaifeizjnonvzbxcpmib.supabase.co:5432/postgres
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: PUBLIC_BASE_URL
        value: https://autosharts-backend.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: TIKTOK_CLIENT_KEY
        sync: false
      - key: TIKTOK_CLIENT_SECRET
        sync: false
      - key: INSTAGRAM_APP_ID
        sync: false
      - key: INSTAGRAM_APP_SECRET
        sync: false
