export enum UserRole {
  USER = 'USER',
  ADMIN = 'ADMIN'
}

export enum ProjectStatus {
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED'
}

export enum SourceVideoStatus {
  UPLOADING = 'UPLOADING',
  UPLOADED = 'UPLOADED',
  PROCESSING = 'PROCESSING',
  PROCESSED = 'PROCESSED',
  ERROR = 'ERROR'
}

export enum ClipStatus {
  CANDIDATE = 'CANDIDATE',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  RENDERING = 'RENDERING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED'
}

export enum CaptionStyle {
  VIRAL = 'VIRAL',
  MODERN = 'MODERN',
  MINIMAL = 'MINIMAL',
  PROFESSIONAL = 'PROFESSIONAL'
}

export enum SocialPlatform {
  TIKTOK = 'TIKTOK',
  INSTAGRAM = 'INSTAGRAM',
  YOUTUBE = 'YOUTUBE'
}

export enum ScheduledPostStatus {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  PUBLISHING = 'PUBLISHING',
  PUBLISHED = 'PUBLISHED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED'
}

export enum JobStatus {
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  RETRYING = 'RETRYING',
  CANCELLED = 'CANCELLED'
}

export enum JobType {
  VIDEO_PROCESSING = 'VIDEO_PROCESSING',
  AUDIO_EXTRACTION = 'AUDIO_EXTRACTION',
  TRANSCRIPTION = 'TRANSCRIPTION',
  AI_CUT_DETECTION = 'AI_CUT_DETECTION',
  CLIP_RENDER = 'CLIP_RENDER',
  METADATA_GENERATION = 'METADATA_GENERATION',
  POST_PUBLISH = 'POST_PUBLISH',
  ANALYTICS_COLLECT = 'ANALYTICS_COLLECT',
  STORAGE_CLEANUP = 'STORAGE_CLEANUP'
}

export enum UsageType {
  AUDIO_TRANSCRIPTION = 'AUDIO_TRANSCRIPTION',
  AI_ANALYSIS = 'AI_ANALYSIS',
  FFMPEG_RENDER = 'FFMPEG_RENDER',
  STORAGE = 'STORAGE'
}

export enum SnapshotWindow {
  ONE_HOUR = '1h',
  SIX_HOURS = '6h',
  TWELVE_HOURS = '12h',
  TWENTY_FOUR_HOURS = '24h',
  FORTY_EIGHT_HOURS = '48h',
  SEVEN_DAYS = '7d'
}

export enum FramingMode {
  FACE_TRACKING = 'FACE_TRACKING',
  SUBJECT_TRACKING = 'SUBJECT_TRACKING',
  VISUAL_FOCUS = 'VISUAL_FOCUS',
  CENTER_CROP = 'CENTER_CROP'
}
